steps:
  # Step 1: Terraform Init (in terraform/ folder)
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    args:
      - -chdir=terraform
      - init

  # Step 2: Terraform Plan
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    args:
      - -chdir=terraform
      - plan
      - -var-file=environments/${_ENV}.tfvars

  # Step 3: Terraform Apply
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    args:
      - -chdir=terraform
      - apply
      - -auto-approve
      - -var-file=environments/${_ENV}.tfvars

substitutions:
  _ENV: dev   # default; overridden in trigger if needed

options:
  logging: CLOUD_LOGGING_ONLY
