steps:
  # Step 1: Terraform Init
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Init'
    args:
      - 'init'

  # Step 2: Terraform Plan
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Plan'
    args:
      - 'plan'
      - '-var-file=environments/${_ENV}-scaling.tfvars'

  # Step 3: Terraform Apply
  - name: 'hashicorp/terraform:1.5.0'
    id: 'Terraform Apply'
    args:
      - 'apply'
      - '-auto-approve'
      - '-var-file=environments/${_ENV}-scaling.tfvars'

substitutions:
  _ENV: 'dev'

options:
  logging: CLOUD_LOGGING_ONLY
