steps:
  # ---------------------------
  # Terraform Init
  # ---------------------------
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    args:
      - "-chdir=terraform"
      - init

  # ---------------------------
  # Terraform Plan
  # ---------------------------
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    args:
      - "-chdir=terraform"
      - plan
      - "-var-file=environments/${_ENV}.tfvars"

  # ---------------------------
  # Terraform Apply
  # ---------------------------
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    args:
      - "-chdir=terraform"
      - apply
      - "-auto-approve"
      - "-var-file=environments/${_ENV}.tfvars"

substitutions:
  _ENV: "dev"   # Default environment (can be overridden per trigger)

options:
  logging: CLOUD_LOGGING_ONLY
