steps:
  # Step 1 — Terraform Init
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - terraform init terraform/

  # Step 2 — Terraform Plan
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - terraform plan -var-file=terraform/environments/${_ENV}.tfvars terraform/

  # Step 3 — Terraform Apply
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - terraform apply -auto-approve -var-file=terraform/environments/${_ENV}.tfvars terraform/

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENV: dev
